添加头像
YunYouJun/web-resume pull request #9
Opened 2023-03-16 02:23 UTC by Akarinnnnn

最大大小为3x3cm

2023-03-16 02:25 UTC, Akarinnnnn commented
#2

2023-03-18 18:58 UTC, YunYouJun requested changes

2023-03-18 18:58 UTC, YunYouJun commented on src/components/resume/Header.vue
> +      <img v-if="resume.basics.avatar" :src="resume.basics.avatar" style="max-height: 3cm; max-width: 3cm;">
I think we can use atomic css directly.

`max-h-3cm`

2023-03-27 10:37 UTC, Akarinnnnn commented on src/components/resume/Header.vue
> +      <img v-if="resume.basics.avatar" :src="resume.basics.avatar" style="max-height: 3cm; max-width: 3cm;">
已修复，另外git hook缺少ts-node-script导致无法Commit

2023-03-27 11:34 UTC, YunYouJun commented on src/components/resume/Header.vue
> +      <img v-if="resume.basics.avatar" :src="resume.basics.avatar" style="max-height: 3cm; max-width: 3cm;">
`max-width` is also needed.

2023-03-27 11:50 UTC, YunYouJun commented
![image](https://user-images.githubusercontent.com/25154432/227933394-c234896f-23a7-4cf4-b713-3e426b2a78f7.png)

When i comment `avatar`, the name is not centered properly, which breaks the style without an avatar.

2023-03-27 12:05 UTC, closed without merging